<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Artimas</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-equal-height.min.js') }}" defer></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
	<style>
		.onn__logo{
			width: 180px;
			height: 80px;
			margin: 30px auto;
		}
		.onn__logo img{
			width: 100%;
			height: 100%;
			object-fit: scale-down;
		}
	</style>
</head>
<body>

    <section class="cart-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="onn__logo">
                        <img src="{{asset('admin/images/artimas-logo.png')}}">
                    </div>
                </div>
                <div class="col-sm-12">
                    <h1 class="text-center mb-3">Privacy Policy</h1>
                    <p>1 GENERAL<br />
                    1.1 Artimas is managing and operating the mobile application/website (collectively referred to as the &ldquo;Artimas &nbsp;B2B&rdquo;) through which it&#39;s the internal sale team will punch their B2B orders.<br />
                    1.2 This privacy policy (&ldquo;Privacy Policy&rdquo;), together with the Terms governs your use of the Artimas B2B and describes our policies and procedures on the collection, use, disclosure, processing, transfer, and storage of the information provided to us by you. By using, browsing, or accessing, the Platform you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure, or transfer of your information under the terms of the Privacy Policy. We shall not use the User&rsquo;s information in any manner except as provided under this Privacy Policy. Capitalized terms used herein if not defined shall have the same meaning as ascribed to them under the Terms.<br />
                    1.3 This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions about electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.<br />
                    1.4 This Privacy Policy sets out the type of information collected from the Users, including the nature of the Sensitive Personal Data or Information (defined hereinafter), the purpose, means, and modes of usage of such information and how and to whom we shall disclose or transfer such information. You may at any time withdraw your consent for collection and use of your information including Personal Information (defined hereinafter) or Sensitive Personal Data or Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Personal Information based on your previous consent before the withdrawal.<br />
                    1.5 Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the Artimas B2B Platform.<br />
                    2 TYPES OF INFORMATION COLLECTED<br />
                    2.1 You may be asked to provide your information anytime you visit, access, use or browse the Artimas B2B Platform. We may share information and use it consistent with the provisions of this Privacy Policy.<br />
                    2.2 You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require the deletion of your information partially or fully by contacting us.<br />
                    2.3 Artimas B2B is not directed toward general users. The application doesn&#39;t have a provision to collect Personal Information from any User who is not an employee of Artimas. If we are made aware that we have collected the Personal Information of a person by any means, we will take steps to delete the information within a reasonable time frame.<br />
                    2.4 We may collect a variety of information from you, including your name, password, mailing address, phone number, email address, &nbsp;and contact preferences, including any other usage and interaction details with us or our affiliates. We may collect such information which when combined with other pieces of information available location with us could reasonably allow you to be identified (&ldquo;Personal Information&rdquo;). Personal Information shall include but is not limited to your full name, personal contact numbers, residential address, email address, gender, or date of birth.<br />
                    3 USE OF INFORMATION COLLECTED<br />
                    3.1 We may collect, use or process your information including Personal Information or Information for the following purposes:<br />
                    3.1.1 For creating and giving you access to your registered account on the Artimas B2B Platform.<br />
                    3.1.2 To develop, deliver, process and improve our Products<br />
                    3.1.3 To inform you about our Products, Schemes, offers, updates, and upcoming events, including providing you the information concerning order confirmations, invoices, technical notices, and security alerts.<br />
                    3.1.4 For internal analysis and research purposes such as auditing, data analysis and research to improve Our Products, services and customer communications.<br />
                    3.1.5 To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.<br />
                    3.1.6 To resolve any request, dispute, grievance or complaint raised by you concerning your use of the Platform.<br />
                    3.1.7 To detect or monitor any fraudulent or illegal activity on the Platform.<br />
                    4 DISCLOSURE OF INFORMATION COLLECTED<br />
                    4.1 We may from time to time be required to disclose the information collected from you to our trusted third-party service providers who assist us to develop and maintenance of the platform. By using the Platform, you consent to any such disclosure of your information with third-party service providers. We ensure that such third-party service providers are bound by reasonable confidentiality obligations and/ or use, maintain and follow generally accepted industry and security standards concerning such information.<br />
                    4.2 We may also disclose your information when such disclosure is requisitioned under any law or judicial decree or when we, in our sole discretion, deem it necessary to protect our rights or the rights of other Users, to prevent harm to persons or property, to fight fraud and credit risk.<br />
                    4.3 We may also disclose or transfer your information to any third party as a part of the reorganization or a sale of the assets, division, or transfer of a part or whole of us. We shall ensure that the third party to which we transfer or sell our assets will have appropriate confidentiality and security measures, at least as protective as those described in this Privacy Policy, to handle your Personal Information. You will have the opportunity to opt out of any such transfer if the new entity&#39;s planned processing of your information differs materially from that outlined in this Privacy Policy.<br />
                    5 SECURITY<br />
                    5.1 The security of your Personal Information is important to us. We have implemented security policies, rules and technical measures, as required under applicable law including firewalls, transport layer security and other physical and electronic security measures to protect the Personal Information that it has under its control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss. When you submit your information on the Platform, your information is protected through our security systems.<br />
                    5.2 Your information is contained within secured networks and is only accessible by a limited number of authorized persons who have access rights to such systems or otherwise require such information for the purposes provided in this Privacy Policy. These authorized persons are also under an obligation to keep such information confidential.<br />
                    5.3 Although we make the best possible efforts to transmit and store all the information provided by you in a secure operating environment that is not open to the public, you understand and acknowledge that there is no such thing as complete security and we do not guarantee that there will be no unintended disclosures of any information and potential security breaches. You agree not to hold us responsible for any breach of security or for any action of any third parties that receive your Personal Information or events that are beyond our reasonable control including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc.<br />
                    6 COOKIES POLICY<br />
                    6.1 The Platform uses temporary cookies to store certain data. We do not store Personal Information in the cookies. Information collected by us, by any means whatsoever, that does not personally identify the User as an individual (such as patterns of utilization described above) is exclusively owned by us and may be used by us and third-party service providers for technical administration of the Platforms, user administration, research, development, and other purposes.<br />
                    6.2 You understand that you may set or amend your web browsers to delete or disable cookies. If you choose to disable cookies on your computer or mobile telecommunication device, it may impair, degrade or restrict access to certain areas of the Platform.<br />
                    6.3 If the User has any concerns with the reproduction/publication of any comment or review provided by you, the User may contact the admin.<br />
                    7 RETENTION OF INFORMATION<br />
                    7.1 We will retain your information and any data for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted under the applicable law.<br />
                    8 MODIFICATION<br />
                    8.1 We reserve the right to amend this Privacy Policy at any time. The Privacy Policy, as and when modified, shall be updated on the Artimas B2B Platform. We encourage you to review this Privacy Policy whenever you visit our Platform to understand how your Personal Information is used.<br />
                    9 GRIEVANCE REDRESSAL<br />
                    9.1 In case, you have any questions, grievances, or complaints about this Privacy Policy or the Platform, you may contact our grievance officer on the below-mentioned details:<br />
                    Call: 8240530173<br />
                    Email: support@Artimas.com<br />
                    10 GOVERNING LAW<br />
                    10.1 The terms of this Privacy Policy shall be governed and construed following the laws of India. Any dispute regarding or arising out of this Privacy Policy shall be subject to the exclusive jurisdiction of the courts in Kolkata, West Bengal.<br />
                    11 SEVERABILITY<br />
                    11.1 Whenever possible, each section of this Privacy Policy shall be interpreted in a manner so as to be valid under applicable law. However, in the event any provision is held to be prohibited or invalid, such provision shall be ineffective only to the extent of such prohibition or invalidity, without invalidating the remainder of such provision or other remaining provisions of this Privacy Policy.</p>
                </div>
            </div>
        </div>
    </section>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
    <script src="{{ asset('js/jquery-equal-height.min.js') }}" defer></script>

</body>
</html>